<nav>
            <ul>
                <li><a href="side2mie.php">Design</a></li>
                <li><a href="side3mie.php">HTML</a></li>
                <li><a href="side4mie.php">Denne hjemmeside</a></li>
                <li><a href="side5mie.php">projekter</a></li>
                <li><a href="side6mie.php">denne hjemmeside </a></li>
                <li><a href="side7mie.php">begrebsordbog</a></li>
                <li><a href="side8mie.php">kilder</a></li>
            </ul>
        </nav>