 <nav>
            <ul>
                <li><a href="side2mie.php">HTML og CSS kortfortalt</a></li>
                <li><a href="side3mie.php">Teori på MMD</a></li>
                <li><a href="side4mie.php">Programmer på MMD</a></li>
                <li><a href="side9mie.php">Andet undervisning</a></li>
                <li><a href="side5mie.php">Projekter</a></li>
                <li><a href="side7mie.php">Historie timen</a></li>
                <li><a href="side6mie.php">Denne hjemmeside</a></li>
                <li><a href="side8mie.php">Kilder</a></li>
            </ul>
        </nav>